### ISSUE TITLE
Meaning of the labels

### ISSUE THREAD

**Issue by quansun** [liyinxiao/LambdaRankNN#4]
Hello, thanks for sharing the algorithm! I'm just wondering, what do the label numbers actually mean in the example. 

Does 0 mean rank position 0; 1 means rank position 1 and so on?

Or 0 actually means irrelevant?

Thanks

**Comment by liyinxiao** [comment]
label means relevance - here is one example of label definition: 
- purchase: label=2
- click: label=1
- no click, no purchase: label=0
