### ISSUE TITLE
Query_id: user_id + item_id

### ISSUE THREAD

**Issue by CoteDave** [liyinxiao/LambdaRankNN#6]
Hi! Not sure how to construct the query_id dataset for a user_id+item_id (2 ids) recommendation problem.  Is it possible to do with LambdaRankNN? Thanks!

**Comment by liyinxiao** [comment]
Not sure I got what you meant.  Query id (qid) represents the grouping of samples - for example, when user enters your website, you recommends a list of items to the user, and the qid for these item impressions should be the same.

**Comment by CoteDave** [comment]
I was refering to an hybrid recommender system approach with the interactions between users and items for exemple. What if the query grouping have multilevel index (user_id × item_id: where the same user can make multiple queries and you want to keep track of each interactions ). In this case the features would contains user features an item features and maybe context features. Then you want to rank the top N items for each user or rank the top N users for each items.

**Comment by liyinxiao** [comment]
I don't think it works for such a hybrid recommendation system. Generally, you need two models, one to rank the top N items for each user, and another one to rank the top N users for each items.
